FROM node:20-alpine

# Criar diretório da aplicação
WORKDIR /app

# Copiar arquivos da aplicação
COPY package*.json ./
COPY src ./src

# Criar a pasta de dados dentro do container
RUN mkdir -p /app/data

# Instalar dependências
RUN npm install

# Expor porta
EXPOSE 8085

# Comando de inicialização
CMD ["npm", "start"]
